import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import Footer from '../components/Footer'

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>calendario</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
    <Footer/>
  </>
}

export default MyApp
