import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/calendar.module.css'

const calendar: NextPage = () => {
    return (
        <div className={styles.general}>
            <Head>
                <title>calendario</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>DIA 1</h1>
                <div>    
                    <table className={styles.tabla1}>
                        <tr>
                            <th scope='row'></th>
                            <th>laboratorios</th>
                            <th>patio</th>
                            <th>otra cosa</th>
                        </tr>
                        <tr>
                            <th>9hs</th>
                            <td>esto</td>
                            <td>esto y aquello</td>
                            <td>nada</td>
                        </tr>
                    </table>
                </div>
            </main>
            
        </div>
    )
}

export default calendar