import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/calendar.module.css'

const Calendar: NextPage = () => {
    return (
        <div className={styles.general}>
            <Head>
                <title>calendario</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>DIA 1</h1>
                <div>    
                    
                </div>
            </main>
        </div>
    )
}

export default Calendar